### ISSUE TITLE
Make build stuck on windows.

### ISSUE THREAD

**Issue by MagicTT** [ricoberger/go-vue-starter#12]
windows X, 
go1.13.10 windows/amd64

PowerShell:

PS E:\GitHub\go-vue-starter> make build
esc -o pkg/static/static.go -pkg static web/vue.js/dist web/mail

Stucked here. Waited for 5 mins and nothing happen. No files like bin/starter show in folder.

**Comment by ricoberger** [comment]
Hi, sorry I'm not able to test this on Windows. Can you try the following please:

```sh
esc -o pkg\static\static.go -pkg static web\vue.js\dist web\mail
go build -o .\bin\starter.exe .\cmd\starter
.\bin\starter.exe
```

Also make sure, that you have build the web app before and have `esc` installed:

```sh
cd go-vue-starter/web/vue.js
yarn install
yarn build
```

```sh
go get -u github.com/mjibson/esc
```

Maybe #7 helps also. If you have any further questions, don't hesitate to ask.

**Comment by sebasijan** [comment]
Hi ricoberger, I was also seeing this issue on widows 10 x64. 

I did the following:

1. installed go, yarn, make, mongoDB
2. yarn install 
3. yarn build (**without this, the dist folder is not created, so it seems its required**)
4. `go get -u github.com/mjibson/esc` from inside `go-vue-starter`

still running `$ make build` throws this error: 

 > esc -o pkg/static/static.go -pkg static web/vue.js/dist web/mail
process_begin: CreateProcess(NULL, esc -o pkg/static/static.go -pkg static web/vue.js/dist web/mail, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:71: static] Error 2

When trying to run the commands you mentioned, this is the output:

1
`'esc' is not recognized as an internal or external command,
operable program or batch file.`

2
` `

3
`time="2020-05-08T21:22:32+01:00" level=info msg="Starting starter (version=, branch=, revision=)"
time="2020-05-08T21:22:32+01:00" level=info msg="Build context (go=go1.14.2, user=, date=)"     `

**Comment by ricoberger** [comment]
Mh it looks like the installation of [esc](https://github.com/mjibson/esc) is failing. Can you check your `GOBIN` path if the `esc` binary is present. Maybe you also have to run `go install`:

```
go get -u github.com/mjibson/esc
go install github.com/mjibson/esc
```

**Comment by MagicTT** [comment]
> Hi, sorry I'm not able to test this on Windows. Can you try the following please:
> 
> ```shell
> esc -o pkg\static\static.go -pkg static web\vue.js\dist web\mail
> go build -o .\bin\starter.exe .\cmd\starter
> .\bin\starter.exe
> ```
> 
> Also make sure, that you have build the web app before and have `esc` installed:
> 
> ```shell
> cd go-vue-starter/web/vue.js
> yarn install
> yarn build
> ```
> 
> ```shell
> go get -u github.com/mjibson/esc
> ```
> 
> Maybe #7 helps also. If you have any further questions, don't hesitate to ask.

Hi Rico,

Sorry for the late reply, but your method worked on my device. Thanks for the help. 

Best

**Comment by sebasijan** [comment]
@ricoberger  I ran both of those commands (both in the project folder and outside) with this output:

    go: golang.org/x/xerrors upgrade => v0.0.0-20191204190536-9bdfabe68543
    go: golang.org/x/tools upgrade => v0.0.0-20200512131952-2bc93b1c0c88

(the install command seems to have done nothing)

running `go env` I can see `GOBIN` is empty :

    set GOBIN=

However, I can see esc.exe in the path `GOPATH/bin`

I guess its a problem with my environment - I don't suppose you have any ideas?

**Comment by ricoberger** [comment]
Mh can you run `go env` and check the value of `GOPATH`. This should be set. Inside the `GOPATH` directory there should be a `bin` folder, where you should found the `esc` binary.

When `GOPATH` is not set you can set it to any directory you want, on macOS and Linux I use the following configuration:

```
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/go
export GO111MODULE=on

export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

I'm not sure how to do this at Windows, but if I get it right from the [docs](https://github.com/golang/go/wiki/SettingGOPATH#windows) you can use:

```
setx GOPATH %USERPROFILE%\go
setx GOBIN %USERPROFILE%\go\bin
```

Maybe this helps also: http://www.wadewegner.com/2014/12/easy-go-programming-setup-for-windows/

**Comment by sebasijan** [comment]
@ricoberger  Thanks Rico, I had to set my bin path explicitly, and also needed to add go/bin to `path` and now it appears to be working. 

Also, thanks for creating this project - its an extremely useful learning tool!

**Comment by ricoberger** [comment]
Nice to hear. I would close the issue then. Feel free to reopen or open a new issue in case of problems.
