### ISSUE TITLE
CORS Request suddenly blocked

### ISSUE THREAD

**Issue by sebasijan** [ricoberger/go-vue-starter#13]
I successfully set the project up on window 10, and requests were definitely working fine - I have signed up, confirmed my email and logged in.

After making some changes to the form layout (no request changes) - I now get an annoying CORS error:

 > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8081/api/v1/account. (Reason: CORS request did not succeed).

I have no idea what I could have changed to cause this, but it was al Vue code, where the request now looks like this:

```
private saveProfile(callbacks: any) {
    let tmpInfo = '';
    if (this.email !== this.user.email) {
      tmpInfo = 'Please verify your new email address';
    }

    callbacks.preSave();

    this.save({name: this.name, email: this.email}).then(() => {
        this.info = tmpInfo;
        callbacks.postSave();
      }).catch((err: any) => {
        callbacks.onError(err.message);
      });
  }
```

Any idea what I should be checking here? It seems to have happened out of nowhere

**Comment by sebasijan** [comment]
After opening this issue, I tried again straight away and it started working - I guess I needed to wait for something to finish loading

**Comment by sebasijan** [comment]
It seems the issue is this:

When getting the CORS error, the app was looking for the api at port 8081 (which is how I would like it configured), and somehow (I don't get this at all) after running starter.exe again, the app is now hosted on 8080 (same as the vue app), and it works. However, the vue app is showing an old cached version.

Is there any guidace on what is going on here? I didnt change any ports or settings, it just seems to be the order in which I run things is affecting this

**Comment by ricoberger** [comment]
Hi, the Vue app expects the API running on a different port for development.

If you run the `yarn serve` it is expected the the server is running at `http://localhost:8081`. The reason for this is, that you have not to run the following commands for each frontend change:

```sh
yarn build
make build
./bin/starter
```

This can be changed in the [constants.ts](https://github.com/ricoberger/go-vue-starter/blob/master/web/vue.js/src/constants.ts#L5) file.

I always changed the `listen_address` and `domain` to `8081` in the [config.yml](https://github.com/ricoberger/go-vue-starter/blob/master/config.yml) file for development.

So `yarn serve` will use port `8081` for API requests and when embedded in the binary no change is necessary.
